services:

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: chope-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./configs/mosquitto:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: chope-influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb2
      - ./configs/influxdb:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=SenhaForte123
      - DOCKER_INFLUXDB_INIT_ORG=taphouse
      - DOCKER_INFLUXDB_INIT_BUCKET=chope
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=meu-token-secreto-de-teste-123456
    restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    container_name: chope-nodered
    ports:
      - "1880:1880"
    volumes:
      - ./volumes/node-red/data:/data
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: chope-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=SenhaForte123
    restart: unless-stopped