[platformio]
; ambiente padrão quando rodar só `pio run` ou `pio run -t upload`
default_envs = esp32dev

; Configuração comum a todos os envs
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bogde/HX711@^0.7.5
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.5
    knolleary/PubSubClient@^2.8

; === FIRMWARE FINAL (usa src/main.cpp) ===
[env:esp32dev]
; usa o src_dir padrão = src
; não precisa de src_filter, compila tudo de src/

; === CALIBRAÇÃO (usa setup/main_calibracao.cpp) ===
[env:calibracao]
; mudar a raiz de código para a raiz do projeto
src_dir = .
; compila só o arquivo de calibração
src_filter = +<setup/main_calibracao.cpp> -<src/>

; === LEITURA DE TESTE (usa setup/main_leitura_definitiva.cpp) ===
[env:leitura_definitiva]
src_dir = .
src_filter = +<setup/main_leitura_definitiva.cpp> -<src/>