# Configuração do Mosquitto (broker MQTT)
# ------------------------------------------
# "listener 1883" diz ao Mosquitto para "escutar" (aceitar conexões)
# na porta 1883, que é a porta padrão do protocolo MQTT.
listener 1883

# "allow_anonymous true" permite conexões SEM usuário/senha por enquanto.
# Isso é só para essa fase de testes na sua máquina local - quando formos
# para o VPS na nuvem (acessível pela internet), vamos OBRIGATORIAMENTE
# trocar isso para exigir autenticação, porque sem senha qualquer pessoa
# na internet poderia se conectar no seu broker.
allow_anonymous true

# Define onde o Mosquitto deve guardar os dados que precisam sobreviver
# a um reinício (ex: mensagens retidas, veremos mais pra frente)
persistence true
persistence_location /mosquitto/data/

# Onde salvar o arquivo de log (histórico de eventos do broker,
# útil para diagnosticar problemas)
log_dest file /mosquitto/log/mosquitto.log