name: CI

on:
  pull_request:

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build ESP32 firmware (all envs)
        working-directory: ./esp32-load-cell-listener
        run: |
          # build all defined envs from platformio.ini
          pio run
          # or explicitly:
          # pio run -e esp32dev -e calibracao -e leitura_definitiva